server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rodrigo-Pressacco/ej-profe-balancer/tree/main/archivos-YML